### ISSUE TITLE
[BUG] The numerical views should stop changing their values when entered for editing.

### ISSUE THREAD

**Issue by TomKovac** [ix-ax/ix#107]
When entering the view of "Control" type, the value should stop changing to be able to overwrite its value. Use polling to replicate.

**Comment by PTKu** [comment]
Branch [107-_BUG_The_numerical_views_should_stop_changing_their_values_when_entered_for_editing](https://github.com/ix-ax/ix/tree/107-_BUG_The_numerical_views_should_stop_changing_their_values_when_entered_for_editing) created!
