### ISSUE TITLE
[NEW-FEATURE] Inconsistence UI behavior when value is changed OnEdit

### ISSUE THREAD

**Issue by Specter-13** [ix-ax/ix#110]

**Comment by PTKu** [comment]
Branch [110-_NEW-FEATURE_Inconsistence_UI_behavior_when_value_is_changed_OnEdit](https://github.com/ix-ax/ix/tree/110-_NEW-FEATURE_Inconsistence_UI_behavior_when_value_is_changed_OnEdit) created!
