### ISSUE TITLE
[NEW-FEATURE] [ixc] Onliner should have method to create an empty POCO object

### ISSUE THREAD

**Issue by Brano5** [ix-ax/ix#122]

**Comment by PTKu** [comment]
Branch [122-_NEW-FEATURE_ixc_Onliner_should_have_method_to_create_an_empty_POCO_object](https://github.com/ix-ax/ix/tree/122-_NEW-FEATURE_ixc_Onliner_should_have_method_to_create_an_empty_POCO_object) created!
