### ISSUE TITLE
[NEW-FEATURE] POCO object should implement `IPlain` or `IPOCO` interface and respective swapping methods

### ISSUE THREAD

**Issue by Brano5** [ix-ax/ix#145]

**Comment by PTKu** [comment]
Branch [145-_NEW-FEATURE_POCO_object_should_implement_IPlain_or_IPOCO_interface_and_respective_swapping_methods](https://github.com/ix-ax/axsharp/tree/145-_NEW-FEATURE_POCO_object_should_implement_IPlain_or_IPOCO_interface_and_respective_swapping_methods) created!
