### ISSUE TITLE
[IXD] Compiler should generate also the enums including their values

### ISSUE THREAD

**Issue by TomKovac** [ix-ax/ix#177]
https://console.simatic-ax.siemens.io/docs/st/language/types-and-variables#data-type-with-named-values
https://console.simatic-ax.siemens.io/docs/st/language/types-and-variables#enumeration

**Comment by PTKu** [comment]
Branch [177-_IXD_Compiler_should_generate_also_the_enums_including_their_values](https://github.com/ix-ax/axsharp/tree/177-_IXD_Compiler_should_generate_also_the_enums_including_their_values) created!
