### ISSUE TITLE
[BUG] impossibility to define an array from any index other than zero

### ISSUE THREAD

**Issue by LukasKytka** [ix-ax/ix#183]
**Describe the bug**
impossibility to define an array from any index other than zero

**To Reproduce**
1. Go to AX project
2. define in AXOpen.Data.AxoDataEntity   aray without zero index (example ArrayStartFromOne : ARRAY[1..7] of BOOL;)
3. compile axsharp then axopen

**Comment by PTKu** [comment]
Branch [183-_BUG_impossibility_to_define_an_array_from_any_index_other_than_zero](https://github.com/ix-ax/axsharp/tree/183-_BUG_impossibility_to_define_an_array_from_any_index_other_than_zero) created!
