### ISSUE TITLE
[BUG] Arrays instantiated in configuration.st transpile incorrectly

### ISSUE THREAD

**Issue by Specter-13** [ix-ax/ix#230]
**Describe the bug**
When I define array in GLOBAL section in configuration.st file, compiler transpiles it with missing information

**To Reproduce**
1. add for example `myArrayString: ARRAY[0..10] OF STRING;` in configuration.st file
2. run ixc
3. build the project and see errors

**Expected behavior**
arrays should be transpiled correctly

**Screenshots**
![image](https://github.com/ix-ax/axsharp/assets/56168909/36f9efc7-6da3-425d-9eef-e548aeaf1cca)

**Comment by PTKu** [comment]
Closed by #232 #215
