### ISSUE TITLE
[BUG] ITwinObject.PlainToOnlineAsync() adds object  properties to cyclic R/W

### ISSUE THREAD

**Issue by kuh0005** [ix-ax/ix#262]
**Describe the bug**

When calling the `PlainToOnlineAsync()` method, values are set over the nested primitive values into the `Cyclic` variable. Subsequently, the entire object is written to the controller using `await this.WriteAsync()`. In the implementation of the Cyclic method, `periodicWriteSet()` is also added, which causes that after the first upload to the controller, the write is duplicated by a periodic write as well.

```csharp
 public virtual T Cyclic
 { ...
     set
     {
         if (HasWriteAccess())
         {
             CyclicToWrite = value;
             _cyclic = value;
             base.Parent.GetConnector()?.AddToPeriodicWriteSet(this);
         }
     }
 }
```

**Comment by PTKu** [comment]
already addressed in #261 
@kuh0005 AXOpen (on https://github.com/ix-ax/AXOpen/pull/257) should be updated, test it and let me know.
