### ISSUE TITLE
[BUG] Encapsulate attributes in a namespace

### ISSUE THREAD

**Issue by kuh0005** [ix-ax/ix#335]
**Describe the bug**
Encapsulate the attributes in a namespace (e.g., GroupAttribute, LayoutAttribute). The TcOpen framework also uses these same attributes, causing conflicts that prevent the compiler from successfully building projects that include both frameworks.

**Comment by kuh0005** [comment]
![image](https://github.com/user-attachments/assets/fb754c85-a2f4-4202-a36d-046bb4d95a01)

**Comment by PTKu** [comment]
Closed in #337
