### ISSUE TITLE
[BUG] Rendering of components from custom library doesn't work

### ISSUE THREAD

**Issue by Specter-13** [ix-ax/ix#45]
Renderer cannot find component in custom library, because compiled C# classes doesn't contains namespaces:

Therefore code,

```
var name = twinType.FullName;
```

will return only type name, not fully qualified name with namespace, therefore comparison will fail and component won't be found.

Also, documentation for custom libraries should be updated.

**Comment by PTKu** [comment]
Branch [45-_BUG_Rendering_of_components_from_custom_library_doesn_t_work](https://github.com/ix-ax/ix/tree/45-_BUG_Rendering_of_components_from_custom_library_doesn_t_work) created!
