### ISSUE TITLE
[IDEA] More integration tests for Blazor renderer

### ISSUE THREAD

**Issue by Specter-13** [ix-ax/ix#47]
It would be nice to have more integration test for Blazor renderer.
Create some structure for tests, specify correct test-cases.
- tests for each basic layout
- tests for groupbox and border group layouts

**Comment by PTKu** [comment]
Branch [47-_IDEA_More_integration_tests_for_Blazor_renderer](https://github.com/ix-ax/ix/tree/47-_IDEA_More_integration_tests_for_Blazor_renderer) created!
