### ISSUE TITLE
[NEW-FEATURE] Compiler should delete previous generated .cs file, if corresponding plc instance is removed

### ISSUE THREAD

**Issue by Specter-13** [ix-ax/ix#62]
When I create plc enum structure (or any structure) and its instance for example:

```
TYPE myEnum :
    (
        Unknown,
        Available,
        UnAvailable	
    );
    END_TYPE
```

```
myEnum_instance : myEnum;
```

Compiler will generate `myEnum.cs` file. That is perfectly okay.

But when I completely remove my `myEnum.st` structure from PLC program, C# compiled file `myEnum.cs` is still present and is causing errors.

It would be nice, if compiler removes unnecessary structures automatically.

**Comment by PTKu** [comment]
Branch [62-_NEW-FEATURE_Compiler_should_delete_previous_generated_cs_file_if_corresponding_plc_instance_is_removed](https://github.com/ix-ax/ix/tree/62-_NEW-FEATURE_Compiler_should_delete_previous_generated_cs_file_if_corresponding_plc_instance_is_removed) created!
