### ISSUE TITLE
[NEW-FEATURE] I'd like to define pragmas on TYPE STRUCT

### ISSUE THREAD

**Issue by TomKovac** [ix-ax/ix#75]
I am not able to add pragmas to TYPE STRUCT

![image](https://user-images.githubusercontent.com/61820360/219335927-1ac9eb22-5d79-4775-9290-6a71b85e3192.png)

**Comment by PTKu** [comment]
@RauerJ, it seems not possible to add pragmas on type declaration. Would it be possible to request this from the AX team?

https://github.com/orgs/simatic-ax/discussions/14

**Comment by RauerJ** [comment]
@PTKu Waiting for the outcome from Jürgen in https://github.com/orgs/simatic-ax/discussions/14 and will create demand depending on answer from devs.

**Comment by PTKu** [comment]
Discussed in https://github.com/orgs/simatic-ax/discussions/14
Closing for now
