### ISSUE TITLE
[NEW-FEATURE] Add possibility to inject css classes into renderer 

### ISSUE THREAD

**Issue by Specter-13** [ix-ax/ix#86]
In some cases, we want to adjust renderer output of generated layouts (e.g. vertical alignment, padding).
It would be nice, if we are able to pass class parameters to children within rendered layout.

**Comment by PTKu** [comment]
Branch [86-_NEW-FEATURE_Add_possibility_to_inject_css_classes_into_renderer](https://github.com/ix-ax/ix/tree/86-_NEW-FEATURE_Add_possibility_to_inject_css_classes_into_renderer) created!
